name = "drive"
type = "webpack"
workers_dev = true
account_id = "4e8570bce455401c744c8ce0de791da2"
zone_id = "cc86f49b275fabe3d32c6a6a6a11ab69"
kv_namespaces = [
    {binding = "BUCKET", id = "5fd72ac727a14e79b8d7a93a33c2cf22", preview_id = "5fd72ac727a14e79b8d7a93a33c2cf22"}
]

[env.staging]
name = "drive-staging"
